### ISSUE TITLE
libsvm data format

### ISSUE THREAD

**Issue by formath** [tobegit3hub/tensorflow_template_application#1]
Hi. I have data set with libsvm format where `feaid`is uint64.  Can you give me an example of how to fetch this data to tensorflow model?  eg. sparse logistic regression. Thanks.
`label feaid:value feaid:value ...`

**Comment by tobegit3hub** [comment]
Sorry for the late reply. Support libsvm data format is the great feature and we will try to implement that soon. Thanks for reporting.
