### ISSUE TITLE
Question about test.

### ISSUE THREAD

**Issue by sailor88128** [tobegit3hub/tensorflow_template_application#12]
I want to output the accuracy with all the train and test data, not the batch_size train and test data. But when I change the  "batch_xtrain" to "xtrain", there is a not match error. Why? What is the right way?

### train_accuracy_logits = inference(batch_xtrain, False) 
train_sigmoid = train_accuracy_logits
train_correct_prediction = tf.equal(tf.argmax(train_sigmoid, 1), tf.argmax(batch_ytrain, 1))
train_accuracy = tf.reduce_mean(tf.cast(train_correct_prediction, tf.float32))

ValueError: Shape must be rank 2 but is rank 1 for 'layer1_1/MatMul' (op: 'MatMul') with input shapes: [440], [440,500].

**Comment by tobegit3hub** [comment]
Can you provide the code of what you have changed?

It seems that you try to inference with rank-one matrix but we need rank-two matrix such as `[batch_size, feature_size]`.

**Comment by sailor88128** [comment]
Thanks for your quick response. 
For example, the following is the origin code in your cancer_classifier.py, what I did is to change _validate_batch_features_ to _validate_features_, _validate_batch_labels_ to _validate_labels_. What I wish to do is to get the accuracy with all the test data, not only the batch_size. And the error appears as the above.

```
Define accuracy op for validate data
validate_accuracy_logits = inference(validate_batch_features, False)
validate_softmax = tf.nn.softmax(validate_accuracy_logits)
validate_batch_labels = tf.to_int64(validate_batch_labels)
validate_correct_prediction = tf.equal(tf.argmax(validate_softmax, 1), validate_batch_labels)
validate_accuracy = tf.reduce_mean(tf.cast(validate_correct_prediction,tf.float32))
```

**Comment by sailor88128** [comment]
![11](https://cloud.githubusercontent.com/assets/20902256/21979489/066a748c-dc1a-11e6-9038-dbeb0604aae9.png)
![12](https://cloud.githubusercontent.com/assets/20902256/21979491/069e66ac-dc1a-11e6-9fd5-e6f7f4daa959.png)

**Comment by tobegit3hub** [comment]
If you want to inference for all test set, you can refer to https://github.com/tobegit3hub/deep_recommend_system/blob/master/dense_classifier.py#L262 .

Using batch validate set is fast but not really accuracy for training. Try to use the code about inference may help if you want to do that for all test set.

**Comment by sailor88128** [comment]
Sorry, I didnot quiet get the point from inference. It seems use placeholder but not the whole dataset used for test.

In addition, the error occurred above still make me confused. Is the method of using tfrecords wrong? If I change the batch size of validation dataset very large, the performance still seems strange, accuracy not converge.

```
  # Define inference op
  inference_features = tf.placeholder("float", [None, FEATURE_SIZE])
  inference_logits = inference(inference_features, False)
  inference_softmax = tf.nn.softmax(inference_logits)
  inference_op = tf.argmax(inference_softmax, 1)
```

**Comment by tobegit3hub** [comment]
Now it doesn't use TFRecords for inference. But I'm trying to add this feature and feel to make a contribution about this.
