### ISSUE TITLE
error with sparse_softmax_cross_entropy_with_logits

### ISSUE THREAD

**Issue by sailor88128** [tobegit3hub/tensorflow_template_application#15]
When run dense_classifier or sparse_classifier, there would be an error as below:
What is the problem? version of python?

  ```
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1684, in sparse_softmax_cross_entropy_with_logits
    labels, logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
```

**Comment by tobegit3hub** [comment]
What's the version of `TensorFlow` that you're using?

I have test with the `0.12.1` and everything should work before this version.

**Comment by sailor88128** [comment]
It's 0.12.head. 
The default python version is 2.7, does it matter?

**Comment by tobegit3hub** [comment]
We have tested with `Python 2.7` and the latest stable TensorFlow versions. Not sure if `0.12.head` has changed the API or not.

Do you mind running this in the latest TensorFlow docker containers? Run like this.

```
 sudo docker run -it -v /:/host tensorflow/tensorflow bash
```

Make sure the version of TensorFlow is latest.

```
python -c "import tensorflow; print(tensorflow.__version__)"
```

Then run with the `./dense_classifier.py` directly. And this should work.

```
./dense_classifier.py
```

If the APIs have changed, I'm glad to follow the latest interfaces.

**Comment by sailor88128** [comment]
Thanks for your respond. I just run docker and it seems need some time. I will try tomorrow.

**Comment by sailor88128** [comment]
I've ran the first command:
 `sudo docker run -it -v /:/host tensorflow/tensorflow bash`
The version of tensorflow is still 0.12.head, and when I run dense_classifier.py, the error is the same.

**Comment by tobegit3hub** [comment]
Thanks for your feedback but it's strange and I don't have this version to test. I will try and test with `TensorFlow 1.0` once it comes out.

**Comment by sailor88128** [comment]
Yeah, thanks.
Do you recommend to update to Tensorflow 1.0 when it comes out?

**Comment by godsarmy** [comment]
This issue can be resolved by following modification

```
diff --git a/distributed/cancer_classifier.py b/distributed/cancer_classifier.py
index d533ae4..d14a239 100755
--- a/distributed/cancer_classifier.py
+++ b/distributed/cancer_classifier.py
@@ -143,7 +143,7 @@ def main(_):

             batch_labels = tf.to_int64(batch_labels)
             cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(
-                logits, batch_labels)
+                logits=logits, labels=batch_labels)
             loss = tf.reduce_mean(cross_entropy, name='xentropy_mean')
             if FLAGS.optimizer == "sgd":
                 optimizer = tf.train.GradientDescentOptimizer(learning_rate)
```

**Comment by tobegit3hub** [comment]
Now this project works for `TensorFlow 1.0.0+` APIs. Please upgrade the TensorFlow and pull the latest code to test again 😃
