### ISSUE TITLE
Binary TensorFlow model server doesn't exist

### ISSUE THREAD

**Issue by manuzhang** [tobegit3hub/tensorflow_template_application#23]
The link to [binary TensorFlow model server](https://github.com/tobegit3hub/deep_recommend_system/blob/master/cpp_predict_server/tensorflow_model_server) in https://github.com/tobegit3hub/deep_recommend_system/blob/master/cpp_predict_server/README.md doesn't exist

**Comment by tobegit3hub** [comment]
Thanks for pointing out.

The binary is too large and has been updated continuously. You can build the binary with `bazel` easily, refer to https://tensorflow.github.io/serving/ .

**Comment by tobegit3hub** [comment]
This file to almost 312M and not sutiable to upload in github.

I have compiled the latest `TensorFlow Serving` with `TensorFlow 1.1.0`. The file is uploaded in object storage and you can download from https://pan.baidu.com/s/1sltwfdr .
