### ISSUE TITLE
benchmark_predict_client.py  doesn't exist

### ISSUE THREAD

**Issue by yangjiao91** [tobegit3hub/tensorflow_template_application#24]
The link [https://github.com/tobegit3hub/deep_recommend_system/tree/master/minimal_model/python_predict_client/benchmark_predict_client.py](https://github.com/tobegit3hub/deep_recommend_system/tree/master/minimal_model/python_predict_client/benchmark_predict_client.py)  doesn't exist

**Comment by tobegit3hub** [comment]
Thanks for reporting. @yangjiao91 

It's divided into two files: [benchmark_qps.py](https://github.com/tobegit3hub/deep_recommend_system/blob/master/minimal_model/python_predict_client/benchmark_qps.py) and [benchmark_latency.py](https://github.com/tobegit3hub/deep_recommend_system/blob/master/minimal_model/python_predict_client/benchmark_latency.py).

**Comment by tobegit3hub** [comment]
For local inference, it's renamed to [benchmark_predict.py](https://github.com/tobegit3hub/deep_recommend_system/blob/master/minimal_model/benchmark_predict.py).

**Comment by tobegit3hub** [comment]
Close and feel free to re-open if there is any question 😃
