### ISSUE TITLE
Model not getting generated ,getting the message as "Do not export the model yet" 

### ISSUE THREAD

**Issue by harithekisan** [tobegit3hub/tensorflow_template_application#37]
Dear Team ,

I am new to tensorflow API , so with these code I am trying to build the model using the below command
I am trying to build the model using the below command, 
./dense_classifier.py --batch_size 1024 --epoch_number 1000 --steps_to_validate 10 --optimizer adagrad --model dnn --dnn_struct "128 32 8"

But with the old code I was able to generate the model successfully ,after the code changes I am not able to generate the model.

From my understanding I have not seen the export_model method in the code, may be because of that model is not being generated, please correct me if I am wrong .

Also please let me know if there is any other step is required to generate the model foder.

Eagerly waiting for your reply. Thank you very much for giving very good project for practice .

Thanking you

**Comment by harithekisan** [comment]
I am able to generate the model without any code change followed the below steps.

Training used the below command,
./dense_classifier.py --batch_size 1024 --epoch_number 1000 --steps_to_validate 10 --optimizer adagrad --model dnn --dnn_struct "128 32 8"

So that checkpoint folder will be created.

During the training in the code export is not happening ,so explicitly we need to export explicitly . For that we need to use the below command.

./dense_classifier.py --batch_size 1024 --epoch_number 1000 --steps_to_validate 10 --optimizer adagrad --model dnn --dnn_struct "128 32 8" --mode savedmodel

After executing the above command I was able to generate the model folder with the specified version.

**Comment by tobegit3hub** [comment]
Great. Thanks for reporting @harithekisan
