### ISSUE TITLE
The readme.md in grpc_service

### ISSUE THREAD

**Issue by burness** [tobegit3hub/tensorflow_template_application#4]
In README.md the inference_server.py and inference_client.py shouldn't be predict_server.py and predict_client.py?

**Comment by tobegit3hub** [comment]
Thanks @burness . That's right and I'm gonna refactor the code of inference services.

**Comment by burness** [comment]
@tobegit3hub  Nice!!! can't wait for it

**Comment by tobegit3hub** [comment]
I have updated the code for gRPC and HTTP inference services.

You can find out the gRPC server in https://github.com/tobegit3hub/deep_recommend_system/tree/master/cpp_predict_server and the gRPC client in https://github.com/tobegit3hub/deep_recommend_system/tree/master/python_predict_client .

Hope it helps 😃
