### ISSUE TITLE
ERROR:root:Get the unsupported parameters, exit now

### ISSUE THREAD

**Issue by ashspencil** [tobegit3hub/tensorflow_template_application#42]
I entried the command after the Run Training
$ ./dense_classifier.py --mode export
And I got this response. 

Trying to search your Flag in the code , I found that there was not a Flag called "export" in Line 66.
And another Flag also couldn't export the report.

Did it just a bug? or I just mistaked something ?

**Comment by tobegit3hub** [comment]
Sorry for the misleading document.

The mode of `export` is changed to `savedmodel` which will export the model as SavedModel file.

Thanks for reporting this @ashspencil 👍
