### ISSUE TITLE
Python gRPC server is not reachable

### ISSUE THREAD

**Issue by CLIsVeryOK** [tobegit3hub/tensorflow_template_application#43]
Does this project support "Python gRPC server"? I open the link in the main page but found error 404.

**Comment by tobegit3hub** [comment]
The code of `Python gRPC server` has been removed since we can use `TensorFlow Serving` for gRPC interface easily.

I will update the README soon and sorry for the bothering.

**Comment by CLIsVeryOK** [comment]
can we use python to build a server so we can use our custom python library, the Tensorflow Serving is C++?

**Comment by tobegit3hub** [comment]
Of course we can. You can try [simple_tensorflow_serving](https://github.com/tobegit3hub/simple_tensorflow_serving) which is implemented in `Python` and we have plan to add gRPC backend in the future.

**Comment by CLIsVeryOK** [comment]
ok, thanks for your kind suggestion.
