### ISSUE TITLE
Tensor slice is too large to serialize

### ISSUE THREAD

**Issue by ericyue** [tobegit3hub/tensorflow_template_application#6]
when input_unit is sparse feature with size 20000000, network is 128*64*64*32
train the model ,it errors "Tensor slice is too large to serialize".

did you try this repo in production system with large data?  

wish some help to slove this. thanks

**Comment by tobegit3hub** [comment]
Thanks for reporting.

It may be the restriction of protobuf. I don't think TensorFlow or deep_recommend_system could solve it. Anyway, you may use model parallelism to split the model into multiple parts so that you don't need to pass 2G+ Variables between servers.

**Comment by tobegit3hub** [comment]
I think it's resolved in the latest TensorFlow and close this because it's not really related to this project.

Thanks for reporting anyway 😃
