### ISSUE TITLE
import tensorflow.serving.Model;

### ISSUE THREAD

**Issue by joyJZhang** [tobegit3hub/tensorflow_template_application#8]
hello ,
import org.tensorflow.framework.TensorProto;
import org.tensorflow.framework.TensorShapeProto;
import tensorflow.serving.Model;
import tensorflow.serving.Predict;
import tensorflow.serving.PredictionServiceGrpc;
 is error.I don not have this package, and tried mvn clean install. how to solve this?thank you !!!

**Comment by tobegit3hub** [comment]
These packaged are generated by protobuf files.

You need to check if `mvn clean install` executes successfully or not. Normally they will be generated as expected.

**Comment by joyJZhang** [comment]
thank you~
I tried mvn clean install again,and downloaded protobuf like this 
 Downloading: http://172.17.102.5:8080/nexus/content/groups/yp3g-snapshot/com/google/protobuf/protoc/3.0.0/protoc-3.0.0.pom

but there still had some problems,
[ERROR] /deep_recommend_system-master/java_predict_client/src/main/proto/predict.proto [0:0]: **tensorflow/core/lib/core/error_codes.proto: File not found.**
tensorflow/core/protobuf/queue_runner.proto: **Import "tensorflow/core/lib/core/error_codes.proto" was not found or had errors.**
tensorflow/core/protobuf/queue_runner.proto:27:12: **"error.Code" is not defined.**

Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project predict: protoc did not exit cleanly.

**Comment by tobegit3hub** [comment]
It seems that you're compiling the non-existing protobuf file and it fails.

I will have a look and checkout why you need this.

**Comment by tobegit3hub** [comment]
I find out that the files in `lib` directory are not added in Github repo. It's blocked by `.gitignore` for Python project.

So I commit to add these file and you can pull the latest code to compile again.

Thanks for reporting this and happy coding 😄
