### ISSUE TITLE
how can i use the trained model to predict my own data?

### ISSUE THREAD

**Issue by terryKing1992** [tobegit3hub/tensorflow_template_application#9]
i use `python manage.py runserver 0.0.0.0:8000` command to start http service, but how can i  use rest client to predict my own data;other words, when i post
http request, what's the content-type(Content-Type: application/x-www-form-urlencoded?) and http body(cancer_features="10,10,10,8,6,1,8,9,1;6,2,1,1,1,1,7,1,1" ?)
 of request, thank you for guidance

**Comment by tobegit3hub** [comment]
Follow the document here https://github.com/tobegit3hub/deep_recommend_system/tree/master/http_service#usage .

You can start the django server with `manage.py` script or `gunicorn`. But I highly recommend to use `gRPC` service instead of HTTP service.

Hope it helps :)
